[project]
name = "lens-pydantic-ai-simple"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "gateway-tracing[httpx2]",
    "opentelemetry-distro",
    "opentelemetry-exporter-otlp-proto-http",
    "pydantic-ai-slim[openai]>=1",
]

[tool.uv.sources]
gateway-tracing = { path = "../../shared/python", editable = true }
