[project]
name = "lens-vercel-ai-sdk-py-swarm"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ai[openai]>=0.8",
    "gateway-tracing[httpx2]",
    "openai>=3",
    "opentelemetry-distro",
    "opentelemetry-exporter-otlp-proto-http",
]

[tool.uv.sources]
gateway-tracing = { path = "../../shared/python" }
