[project]
name = "lens-google-adk-simple"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "gateway-tracing[httpx]",
    "openai",
    "google-adk",
    "litellm",
    "openinference-instrumentation-google-adk",
    "opentelemetry-distro",
    "opentelemetry-exporter-otlp-proto-http",
]

[tool.uv.sources]
gateway-tracing = { path = "../../shared/python", editable = true }
